#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /front
  controller: App\Controller\Front\IndexController::index
homeadmin:
  path: /back
  controller: App\Controller\Admin\AdminController::index